### ISSUE TITLE
Noah: A service to map Rampart IDs to Portal IDs

### ISSUE THREAD

**Issue by kevinmichaelchen** [TeslaGov/joan#8]
In commit 237adfb4147508a55bfedb2db44022410d964dc7, I realized that we needed an intermediate service to map from Rampart IDs to Portal IDs. The problem is that right after we create a resource in Rampart, we cannot force Portal to use Rampart's IDs, since Portal creates its own IDs. This is a problem for a couple reasons, one of them being that when our hook goes to add a user to a role, it is only given Rampart IDs: a personUUID and a roleUUID. Neither of those IDs are sufficient to perform a legal addUserToGroup operation, since what we really need are the "username" and "groupID" as Portal sees them.

The fix would be to create a simple mapping service (call it Noah) that maps Rampart resource IDs to Arc IDs. The flow would then look like this: (1) rampart-joan-hook passes the Rampart IDs to the appropriate endpoint in Noah, (2) Noah makes the appropriate call to Portal with the Joan Java SDK and persists any mappings between Rampart IDs and Portal IDs (e.g., personUUID to username, and roleUUID to groupID).

**Comment by kevinmichaelchen** [comment]
@fitzyjoe Suppose we have a `Role` in Rampart with an ID of `60117ba6-1ec3-4691-bb7c-02a25e0279d3`, and we have my `Person` with an ID of `6b356c93-87ee-4960-80f2-786257b6392f`.

AFAIK, when we create a group in Portal (via their REST API) that corresponds to Role `60117ba6-1ec3-4691-bb7c-02a25e0279d3`, we cannot provide the groupID (see the [createGroup](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Create_Group/02r30000009w000000/) docs). Portal will create the ID for a group and include that in its response.

When we create a user in Portal, we are supposed to provide the `username`. But the reason we need an extra datastore is because Rampart should not keep track of ArcGIS-related IDs. We need another service that can map `60117ba6-1ec3-4691-bb7c-02a25e0279d3` to `somePortalGroupID` and `6b356c93-87ee-4960-80f2-786257b6392f` to `kevin.chen`.

**Comment by fitzyjoe** [comment]
What do you think about looking up the group and user by name using the API before adding a user to a group?  Then we don't store it.

**Comment by kevinmichaelchen** [comment]
That might work. They have endpoints for [group search](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Group_Search/02r3000000m1000000/) and [user search](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/User_Search/02r3000000m6000000/). However, the Portal docs issue a warning about "looking for specific records programmatically":
> Care should be taken when using ArcGIS REST API search operations to find items, groups, and users programmatically. The Portal uses a powerful search engine to index information and to allow full text searching on it. This search engine uses many different inputs to find the appropriate results and rank them. This often makes search 'fuzzy', making it ideal for human interaction, but not necessarily ideal for looking for specific records programmatically. Developers should avoid using search to find specific items (e.g. by title) as the results of these types of queries might change as the search engine evolves.

**Comment by kevinmichaelchen** [comment]
Additionally, Noah would store Portal users' passwords, since Rampart would not be allowed to do this.

**Comment by fitzyjoe** [comment]
You know how the pixplus creates accounts with the same huge password for
every user in mediawiki.  I was thinking of doing the same thing... if we
even have to supply a password.  The reverse proxy validate the JWT, and
then our enhancement to ArcGIS is going to trust the username and set that
on an upstream header.
